//Tmo config
pCalibDb->ahdr.merge.mode = 2;
pCalibDb->ahdr.merge.envLevel[0] = 1;
pCalibDb->ahdr.merge.envLevel[1] = 1;
pCalibDb->ahdr.merge.envLevel[2] = 1;
pCalibDb->ahdr.merge.envLevel[3] = 1;
pCalibDb->ahdr.merge.envLevel[4] = 1;
pCalibDb->ahdr.merge.envLevel[5] = 1;
pCalibDb->ahdr.merge.oeCurve_smooth[0] = 80;
pCalibDb->ahdr.merge.oeCurve_smooth[1] = 80;
pCalibDb->ahdr.merge.oeCurve_smooth[2] = 80;
pCalibDb->ahdr.merge.oeCurve_smooth[3] = 80;
pCalibDb->ahdr.merge.oeCurve_smooth[4] = 80;
pCalibDb->ahdr.merge.oeCurve_smooth[5] = 80;
pCalibDb->ahdr.merge.oeCurve_offset[0] = 205;
pCalibDb->ahdr.merge.oeCurve_offset[1] = 205;
pCalibDb->ahdr.merge.oeCurve_offset[2] = 205;
pCalibDb->ahdr.merge.oeCurve_offset[3] = 205;
pCalibDb->ahdr.merge.oeCurve_offset[4] = 205;
pCalibDb->ahdr.merge.oeCurve_offset[5] = 205;

pCalibDb->ahdr.merge.moveCoef[1] = 1;
pCalibDb->ahdr.merge.moveCoef[2] = 1;
pCalibDb->ahdr.merge.moveCoef[3] = 1;
pCalibDb->ahdr.merge.moveCoef[4] = 1;
pCalibDb->ahdr.merge.moveCoef[5] = 1;
pCalibDb->ahdr.merge.moveCoef[0] = 1;
pCalibDb->ahdr.merge.mdCurveLm_smooth[0] = 80;
pCalibDb->ahdr.merge.mdCurveLm_smooth[1] = 80;
pCalibDb->ahdr.merge.mdCurveLm_smooth[2] = 80;
pCalibDb->ahdr.merge.mdCurveLm_smooth[3] = 80;
pCalibDb->ahdr.merge.mdCurveLm_smooth[4] = 80;
pCalibDb->ahdr.merge.mdCurveLm_smooth[5] = 80;
pCalibDb->ahdr.merge.mdCurveLm_offset[0] = 38;
pCalibDb->ahdr.merge.mdCurveLm_offset[1] = 38;
pCalibDb->ahdr.merge.mdCurveLm_offset[2] = 38;
pCalibDb->ahdr.merge.mdCurveLm_offset[3] = 38;
pCalibDb->ahdr.merge.mdCurveLm_offset[4] = 38;
pCalibDb->ahdr.merge.mdCurveLm_offset[5] = 38;
pCalibDb->ahdr.merge.mdCurveMs_smooth[0] = 80;
pCalibDb->ahdr.merge.mdCurveMs_smooth[1] = 80;
pCalibDb->ahdr.merge.mdCurveMs_smooth[2] = 80;
pCalibDb->ahdr.merge.mdCurveMs_smooth[3] = 80;
pCalibDb->ahdr.merge.mdCurveMs_smooth[4] = 80;
pCalibDb->ahdr.merge.mdCurveMs_smooth[5] = 80;
pCalibDb->ahdr.merge.mdCurveMs_offset[0] = 38;
pCalibDb->ahdr.merge.mdCurveMs_offset[1] = 38;
pCalibDb->ahdr.merge.mdCurveMs_offset[2] = 38;
pCalibDb->ahdr.merge.mdCurveMs_offset[3] = 38;
pCalibDb->ahdr.merge.mdCurveMs_offset[4] = 38;
pCalibDb->ahdr.merge.mdCurveMs_offset[5] = 38;

pCalibDb->ahdr.merge.oeCurve_damp = 0.3;
pCalibDb->ahdr.merge.mdCurveLm_damp = 0.3;
pCalibDb->ahdr.merge.mdCurveMs_damp = 0.3;


//Tmo config
pCalibDb->ahdr.tmo.envLevel[0] = 0;
pCalibDb->ahdr.tmo.envLevel[1] = 0.2;
pCalibDb->ahdr.tmo.envLevel[2] = 0.4;
pCalibDb->ahdr.tmo.envLevel[3] = 0.6;
pCalibDb->ahdr.tmo.envLevel[4] = 0.8;
pCalibDb->ahdr.tmo.envLevel[5] = 1;
pCalibDb->ahdr.tmo.globalLuma[0] = 307;
pCalibDb->ahdr.tmo.globalLuma[1] = 255;
pCalibDb->ahdr.tmo.globalLuma[2] = 215;
pCalibDb->ahdr.tmo.globalLuma[3] = 184;
pCalibDb->ahdr.tmo.globalLuma[4] = 144;
pCalibDb->ahdr.tmo.globalLuma[5] = 102;
pCalibDb->ahdr.tmo.globalMaxLuma[0] = 512;
pCalibDb->ahdr.tmo.globalMaxLuma[1] = 460;
pCalibDb->ahdr.tmo.globalMaxLuma[2] = 378;
pCalibDb->ahdr.tmo.globalMaxLuma[3] = 307;
pCalibDb->ahdr.tmo.globalMaxLuma[4] = 255;
pCalibDb->ahdr.tmo.globalMaxLuma[5] = 204;

pCalibDb->ahdr.tmo.OEPdf[0] = 0;
pCalibDb->ahdr.tmo.OEPdf[1] = 0.1;
pCalibDb->ahdr.tmo.OEPdf[2] = 0.2;
pCalibDb->ahdr.tmo.OEPdf[3] = 0.3;
pCalibDb->ahdr.tmo.OEPdf[4] = 0.4;
pCalibDb->ahdr.tmo.OEPdf[5] = 0.5;
pCalibDb->ahdr.tmo.detailsHighLight[0] = 512;
pCalibDb->ahdr.tmo.detailsHighLight[1] = 409;
pCalibDb->ahdr.tmo.detailsHighLight[2] = 258;
pCalibDb->ahdr.tmo.detailsHighLight[3] = 307;
pCalibDb->ahdr.tmo.detailsHighLight[4] = 256;
pCalibDb->ahdr.tmo.detailsHighLight[5] = 204;

pCalibDb->ahdr.tmo.enLumaWeight = 0;
pCalibDb->ahdr.tmo.DarkPdfTH = 0.7;
for(int i = 0; i < 225; i++)
    pCalibDb->ahdr.tmo.LumaWeight[i] = 1;
pCalibDb->ahdr.tmo.DarkTexturePdf[0] = 0;
pCalibDb->ahdr.tmo.DarkTexturePdf[1] = 0.1;
pCalibDb->ahdr.tmo.DarkTexturePdf[2] = 0.2;
pCalibDb->ahdr.tmo.DarkTexturePdf[3] = 0.3;
pCalibDb->ahdr.tmo.DarkTexturePdf[4] = 0.4;
pCalibDb->ahdr.tmo.DarkTexturePdf[5] = 1;
pCalibDb->ahdr.tmo.detailsLowLight[0] = 16;
pCalibDb->ahdr.tmo.detailsLowLight[1] = 32;
pCalibDb->ahdr.tmo.detailsLowLight[2] = 40;
pCalibDb->ahdr.tmo.detailsLowLight[3] = 48;
pCalibDb->ahdr.tmo.detailsLowLight[4] = 56;
pCalibDb->ahdr.tmo.detailsLowLight[5] = 63;

pCalibDb->ahdr.tmo.enPosWeight = 0;
for(int i = 0; i < 225; i++)
    pCalibDb->ahdr.tmo.PosWeight[i] = 1;
pCalibDb->ahdr.tmo.PosCoef[0] = 0;
pCalibDb->ahdr.tmo.PosCoef[1] = 0.2;
pCalibDb->ahdr.tmo.PosCoef[2] = 0.4;
pCalibDb->ahdr.tmo.PosCoef[3] = 0.6;
pCalibDb->ahdr.tmo.PosCoef[4] = 0.8;
pCalibDb->ahdr.tmo.PosCoef[5] = 1;
pCalibDb->ahdr.tmo.noiseLowLight[0] = 1;
pCalibDb->ahdr.tmo.noiseLowLight[1] = 5;
pCalibDb->ahdr.tmo.noiseLowLight[2] = 10;
pCalibDb->ahdr.tmo.noiseLowLight[3] = 40;
pCalibDb->ahdr.tmo.noiseLowLight[4] = 70;
pCalibDb->ahdr.tmo.noiseLowLight[5] = 100;

pCalibDb->ahdr.tmo.DynamicRange[0] = 1;
pCalibDb->ahdr.tmo.DynamicRange[1] = 44;
pCalibDb->ahdr.tmo.DynamicRange[2] = 66;
pCalibDb->ahdr.tmo.DynamicRange[3] = 72;
pCalibDb->ahdr.tmo.DynamicRange[4] = 78;
pCalibDb->ahdr.tmo.DynamicRange[5] = 84;
pCalibDb->ahdr.tmo.DayTh = 0.5;
pCalibDb->ahdr.tmo.smoothControlCoef1[0] = 0;
pCalibDb->ahdr.tmo.smoothControlCoef1[1] = 0;
pCalibDb->ahdr.tmo.smoothControlCoef1[2] = 128;
pCalibDb->ahdr.tmo.smoothControlCoef1[3] = 235;
pCalibDb->ahdr.tmo.smoothControlCoef1[4] = 255;
pCalibDb->ahdr.tmo.smoothControlCoef1[5] = 255;
pCalibDb->ahdr.tmo.smoothControlCoef2[0] = 76;
pCalibDb->ahdr.tmo.smoothControlCoef2[1] = 76;
pCalibDb->ahdr.tmo.smoothControlCoef2[2] = 76;
pCalibDb->ahdr.tmo.smoothControlCoef2[3] = 76;
pCalibDb->ahdr.tmo.smoothControlCoef2[4] = 76;
pCalibDb->ahdr.tmo.smoothControlCoef2[5] = 76;

pCalibDb->ahdr.tmo.damp = 0.3;

